name: Hello Git Actions

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: self-hosted
    steps:
      - name: Echo the message
        run: |
          echo "Hola Fas!"
      - name: pwd
        run: |
          pwd


