name: Deploy app

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened,synchronize]
      

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Cancel previous builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Test e2e
        if: false
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-test
          wait-on: http://localhost:5000

  